### ISSUE TITLE
Failed to dynamically fetch target download uri.

### ISSUE THREAD

**Issue by archmangler** [microsoft/botframework-sdk#5641]
When trying to download the bot code from the "Build" section of the portal I get this error:

```
Failed to dynamically fetch target download uri.
```

There is no way to debug further from the portal. How to debug further?

**Comment by CoHealer** [comment]
@archmangler, the Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). The official [Bot Framework Github](https://github.com/Microsoft/BotBuilder/blob/master/README.md) repos are the preferred platform for submitting **bug fixes** and **feature requests**.

**Comment by dmvtech** [comment]
This is a bug and should be resolved shortly if not already.

**Comment by archmangler** [comment]
FYI, I'm still seeing this issue in current bot deployments.

**Comment by dmvtech** [comment]
@archmangler Does it happen consistently with the same bot (after waiting for a few minutes, etc)? Does it happen with more than one bot?

**Comment by dmvtech** [comment]
Additionally, do you have a custom domain in Azure that you are using for your bots?
